version: 2.1

# Make sure you use the latest version of the Orb!
orbs:
  rn: react-native-community/react-native@2.0.1

# Custom jobs which are not part of the Orb
jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .
  analyse_js:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Run ESLint
          command: yarn eslint
      - run:
          name: Flow
          command: yarn flow

workflows:
  test:
    jobs:
      - analyse_js:
          requires:
            - checkout_code
      - rn/ios_build:
          name: build_ios_release
          project_path: ios/EpicCycling.xcodeproj
          device: "iPhone X"
          build_configuration: Release
          scheme: EpicCycling
          requires:
            - analyse_js