export const LIST_OF_STATIONS_REQUEST = 'LIST_OF_STATIONS_REQUEST';
export const LIST_OF_STATIONS_SUCCESS = 'LIST_OF_STATIONS_SUCCESS';
export const LIST_OF_STATIONS_FAILURE = 'LIST_OF_STATIONS_FAILURE';

export const LIST_OF_BICYCLES_REQUEST = 'LIST_OF_BICYCLES_REQUEST';
export const LIST_OF_BICYCLES_SUCCESS = 'LIST_OF_BICYCLES_SUCCESS';
export const LIST_OF_BICYCLES_FAILURE = 'LIST_OF_BICYCLES_FAILURE';